[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_repr = "0.1"
